# plugin version numbers in this demo may not reflect the latest available versions
- label: ":docker: build"
  key: docker-build
  command: docker build -t tt-testdeployment --file Dockerfile .
  plugins:
    - twilio-internal/container-registry#v1.2.1:
        image:
          docker: tt-testdeployment
- label: "Render deployment manifest for dev"
  key: deploy-dev
  depends_on: docker-build
  agents:
    queue: otk-manifest-renderer
  plugins:
    - ecr#v2.7.0:
        login: true
        account_ids: "018537234677"
        region: "us-east-1"
    - twilio-internal/render-manifests#v0.0.29:
        gitops_repo: git@github.com:twilio-internal/tt-testdeployment-deploy.git
        render:
          - helm:
              source: chart
              destination: environments/dev/us-east-1
              values_files:
                - values.yaml
                - values-dev.yaml
                - values-dev-us-east-1.yaml
              release_name: tt-testdeployment
              set_values:
                - key: 'twilhelm.containerInfo.image.version'
                  value: "$(buildkite-agent meta-data get container-images/v2/tt-testdeployment/us-east-1/tag)"
                - key: 'twilhelm.containerInfo.image.repo'
                  value: "$(buildkite-agent meta-data get container-images/v2/tt-testdeployment/us-east-1/repository)"